home:
    path: /
    controller: App\Controller\HomeController::home
    methods: [GET]

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

provide_2fa_code:
    path: /login/2fa
    controller: App\Controller\LoginController::twoFactorAuthentication
    methods: [GET, POST]

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
    methods: [GET]

profile_security: # enable/disable 2fa, change password
    path: /profile/security
    controller: App\Controller\ProfileController::security
    methods: [GET, POST]

rss_list:
    path: /rss
    controller: App\Controller\RssController::list
    methods: [GET]

rss_add_subscription:
    path: /rss/add
    controller: App\Controller\RssController::add
    methods: [GET, POST]

rss_subscription:
    path: /rss/subscription/{id}
    controller: App\Controller\RssController::subscription
    methods: [GET]

rss_remove_subscription:
    path: /rss/subscription/{id}/remove
    controller: App\Controller\RssController::remove
    methods: [GET, POST]

rss_refresh_subscription:
    path: /rss/subscription/{id}/refresh
    controller: App\Controller\RssController::refresh
    methods: [GET]

rss_article:
    path: /rss/subscription/{id}/article/{url}
    controller: App\Controller\RssController::article
    methods: [GET]

files:
    path: /files
    controller: App\Controller\FilesController::root
    methods: [GET]

files_trash:
    path: /files/trash
    controller: App\Controller\FilesController::trash
    methods: [GET, POST]

files_directory:
    path: /files/{directory}
    controller: App\Controller\FilesController::directory
    methods: [GET]

file_delete:
    path: /files/{file}/delete
    controller: App\Controller\FilesController::delete
    methods: [POST]

file_delete:
    path: /files/{file}/restore
    controller: App\Controller\FilesController::restore
    methods: [POST]

files_download:
    path: /files/{file}/download
    controller: App\Controller\FilesController::download
    methods: [GET]

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::list
    methods: [GET]

calendar_agenda:
    path: /calendar/{agenda}
    controller: App\Controller\CalendarController::agenda
    methods: [GET]

calendar_agenda_add:
    path: /calendar/{agenda}/add
    controller: App\Controller\CalendarController::addAgenda
    methods: [GET, POST]

calendar_agenda_delete:
    path: /calendar/{agenda}
    controller: App\Controller\CalendarController::deleteAgenda
    methods: [DELETE]

calendar_event_add:
    path: /calendar/{agenda}/event
    controller: APp\Controller\CalendarController::addEvent
    methods: [GET, POST]

calendar_event:
    path: /calendar/{agenda}/event/{event}
    controller: App\Controller\CalendarController::event
    methods: [GET, POST, PUT]

calendar_event_cancel:
    path: /calendar/{agenda}/event/{event}/cancel
    controller: App\Controller\CalendarController::cancelEvent
    methods: [GET, POST]
